server:
  port: 8080

custom:
  site:
    name: "ilta_dev"
    cookieDomain: localhost
    frontUrl: "http://localhost:5173"
    backUrl: "http://localhost:8080"

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hikari:
    maximum-pool-size: 10
    minimum-idle: 10
    idle-timeout: 300000
    connection-timeout: 30000
    max-lifetime: 1500000

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
