server:
  port: ${PORT:10000}   # Render 기본 포트
  address: 0.0.0.0

kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    redirect: ${KAKAO_REDIRECT_URL}

spring:
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
