server:
  port: 8080

kakao:
  auth:
    client: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirect: ${KAKAO_REDIRECT_URL}

spring:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 10

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
